sudo: required

services: docker

language: c

os:
  - linux

compiler:
  - gcc

before_install:
  - echo $PWD
  - git rev-parse --abbrev-ref HEAD
  - git checkout $TRAVIS_BRANCH
  #
  # 'make travis-docker-image' reads the branch name
  # <travis>-<distro>-<rel>  or default to Fedora 27
  #
  - make travis-docker-image
  - git fetch --tags
  - git fetch --depth=100000
  - make travis-docker-start
  #- sudo docker exec -ti swanbase  /bin/bash -c 'cd /home/build/libreswan && make showdebversion'

script:
  - make travis-docker-make
  - make travis-docker-make-install
